spid_metadata:
  path: /metadata
  defaults: { _controller: SpidSymfonyBundle:Security:metadata }
  methods:
    - 'GET'

spid_chooseidp:
  path: /idp
  defaults: { _controller: SpidSymfonyBundle:Security:chooseidp }
  methods:
    - 'GET'

spid_login:
  path: /login
  defaults: { _controller: SpidSymfonyBundle:Security:login }
  methods:
    - 'GET'
    -
spid_acs:
  path: /acs
  defaults: { _controller: SpidSymfonyBundle:Security:acs }
  methods:
    - 'POST'

